### ISSUE TITLE
AzureInformationProtection does not work

### ISSUE THREAD

**Issue by vrdse** [PowerShell/PowerShellModuleCoverage#12]
Steps to reproduce
------------------

```powershell
Import-Module "C:\Program Files (x86)\Microsoft Azure Information Protection\Powershell\AzureInformationProtection"
Get-ChildItem | ForEach-Object { Get-AIPFileStatus $_.FullName }
```

Expected behavior
-----------------

```none
An object of the `Microsoft.InformationProtection.Powershell.AIP.Results.GetAIPFileStatusResult` is returned for each item.
```

Actual behavior
---------------

```none
The following error is thrown for each item.

PSMessageDetails      :
Exception             : System.TypeInitializationException: The type initializer for 'NLog.LogManager' threw an exception.
                         ---> System.TypeInitializationException: The type initializer for 'NLog.LogFactory' threw an exception.
                         ---> System.MissingMethodException: Method not found: 'System.String System.AppDomainSetup.get_ConfigurationFile()'.
                           at NLog.Internal.Fakeables.AppDomainWrapper..ctor(AppDomain appDomain)
                           at NLog.Internal.Fakeables.AppDomainWrapper.get_CurrentDomain()
                           at NLog.LogFactory.get_CurrentAppDomain()
                           at NLog.LogFactory..cctor()
                           --- End of inner exception stack trace ---
                           at NLog.LogFactory..ctor()
                           at NLog.LogManager..cctor()
                           --- End of inner exception stack trace ---
                           at NLog.LogManager.GetLogger(String name)
                           at Microsoft.InformationProtection.Lib.NLogConfiguration.GetAssemblyLogger()
                           at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Lazy`1.CreateValue()
                           at Microsoft.InformationProtection.Powershell.AIP.Commandlets.AIPBaseCmdlet.HandleTerminatingException(Exception ex, ErrorCategory errorCategory, String message, Exception forwardException, Object target,
                        String errorId, Boolean isAnError)
                           at Microsoft.InformationProtection.Powershell.AIP.Commandlets.AIPBaseScannerCmdlet.BeginProcessing()
                           at System.Management.Automation.Cmdlet.DoBeginProcessing()
                           at System.Management.Automation.CommandProcessorBase.DoBegin()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-AIPFileStatus], TypeInitializationException
FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.InformationProtection.Powershell.AIP.Commandlets.GetAIPFileStatusCmdLet
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.3
PSEdition                      Core
GitCommitId                    7.0.0-preview.3
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
AzureInformationProtection module version:
ModuleVersion = '2.2.19.0'

**Comment by rjmholt** [comment]
It looks like this isn't a Windows feature module but one that comes with an installable application (i.e. it isn't installed to `%windir%\System32\WindowsPowerShell\v1.0\Modules`) &mdash; which are the modules this repo covers.

It looks like the current implementation depends on [`AppDomainSetup.ConfigurationFile`](https://docs.microsoft.com/en-us/dotnet/api/system.appdomainsetup.configurationfile?view=netframework-4.8&viewFallbackFrom=netcore-3.0) which .NET Core 3.0 does not support.

I think the right way to go is to request support for PowerShell 7 [here](https://msip.uservoice.com/forums/600097-azure-information-protection).

**Comment by vrdse** [comment]
That's correct, the module is not part of Windows. I remember @SteveL-MSFT  used a more generic description for this repo in a blog post, hence I raised the issue here. If you close the issue here for the said reason that's also okay for me.

**Comment by SteveL-MSFT** [comment]
@vrdse please provide feedback to the Azure Information Protection team via Uservoice.  We can keep this issue here to track what works and what doesn't.
